### ISSUE TITLE
Unprimed program variables occur in conclusion after running diffInd

### ISSUE THREAD

**Issue by nrfulton** [LS-Lab/KeYmaeraX-release#1]
The diffInd tactic does not add x'=0 for programVariables that do not occur primed in an ODE. This may affect other differential tactics.

To Reproduce, run `implyR(1) & diffInd(1)` on this model:

```
ProgramVariables.
  R x.
  R y.
End.
Problem.
  y>=0 -> [{x'=y}](y>=0)
End.
```

Edit: The solution isn't to literally add x'=0 but rather  to consttify. Note that this was working properly in 4.1b2.

Edit 2: A temporary workaround is to add `x' = 0` to your model for all non-primed programVariables.

**Comment by bbohrer** [comment]
It isn't supposed to add x'=0 though, is it? I would expect it to constify y to y() after which the axiom (_x())' = 0 would give you y()' = 0.

Or do you mean to say that diffInd does not constify y?

**Comment by nrfulton** [comment]
Right, it doesn't constify. That seemed like an esoteric thing to say; I wanted the bug report to be readable by users who are having this issue so that they know we know :-)

**Comment by bbohrer** [comment]
Sorry, I can only understand the most esoteric bug reports :-)

**Comment by smitsch** [comment]
With auto='full it does constify. With auto='diffInd and auto='none, it's the user's explicit wish to go manually, so it doesn't constify.

**Comment by nrfulton** [comment]
Are there situations where web ui users would _not_ want to constify? For example, a manual diffInd on this goal:

`x=1&v=2&a=3&t=0 -> [{x'=v,v'=a,t'=1&true&v=3*t+2}]x=1 + (a/2)*t^2 + 2*t`

will produce something like `v=0+(a'·2-a·0)/22·t2+a/2·2·t(2-1)·1+2·1` where the `a'` is not mentioned anywhere else in the sequent. Which is a pretty useless subgoal since in almost all cases you won't be able to prove anything about it. I can't think of a situation where not constifying the expected/intuitive behavior.

Allowing non-constify from the tactics library makes sense, but I propose always doing constify whenever a tactic is called from the web ui.

**Comment by aplatzer** [comment]
I think the right behavior for differential invariants would eventually be to always do 
```
    *
------------------ QE
pure arithmetic
---------------------------------------- [':=]
 |= [x':=f(x)] result-of-computing (p(x))'
--------------------------------------- dI
... |- [x'=f(x)]p(x)

```
That would make it all very transparent and traceable. And the user can mess around in the QE step if that doesn't work outright on its own.

In particular, Dconstify is always the right thing to do on the UI. The subtle bit is that unless primed variables end up quantifiable, it's a bit difficult to literally produce the form 
[x':=f(x)]result of (p(x))'. It'd be a lot easier to already apply [':=] even if that's sadly a lot less traceable :-(

**Comment by nrfulton** [comment]
I think various tactics interface improvements resolved this issue.
