### ISSUE TITLE
Mathematica and Wolfram Engine Configuration

### ISSUE THREAD

**Issue by umerhuzaifa** [LS-Lab/KeYmaeraX-release#108]
On every run, I have to go to `Preferences` to configure the paths for Wolfram Engine or Mathematica. However, every time as I press `Save`, the software just hangs. I have tried updating the `.conf` file as well with the correct paths for `JLink` and `MathKernel` too but to no avail. I am using a Windows 10 operating system.

![image](https://user-images.githubusercontent.com/7833132/168381017-98b15e6a-eecb-4754-bce8-7f26029dc04a.png)

**Comment by smitsch** [comment]
It seems that the connection to Mathematica is blocked. Please try the following configuration options:
* try toggling true/false; connection over TCPIP is sometimes more stable, but if true, a firewall may block the connection
```MATH_LINK_TCPIP = true```
* check the library paths in keymaerax.conf and check file access rights
```MATHEMATICA_LINK_NAME = C:\path\including\MathKernel.exe``` path must include MathKernel.exe
```MATHEMATICA_JLINK_LIB_DIR = C:\path\to\JLinkNativeLibrary.dll``` path must not include JLinkNativeLibrary.dll
* is KeYmaera X executed from a folder or with a user that has limited access rights to the user home directory?
* is the Mathematica license local or obtained from a license server? if license server, could something block access to it?
