### ISSUE TITLE
EquivRewriting sometimes fails with new unification

### ISSUE THREAD

**Issue by nrfulton** [LS-Lab/KeYmaeraX-release#20]
See the ignored rests cases in the EquivRewriting tests.

I think this happens because new unification requires subst over rename, but equiv rewriting requires renaming above subst (otherwise subst gets too clever).

**Comment by smitsch** [comment]
It's the complicated cases of the form x=0 used to rewrite x*y=x, where the result could be 0*y=0 or 0*y=x or x*y=0 depending on where (top-level or left x or right x) the rewriting was applied.
