### ISSUE TITLE
sbt assembly sets wrong symlink to keymaerax.jar  

### ISSUE THREAD

**Issue by kghorbal** [LS-Lab/KeYmaeraX-release#30]
after compiling the new version, the symlink of keymaerax.jar got updated to nfulton personal path. 

fool@bar:~/keymaerax$ ls -l keymaerax.jar 
lrwxr-xr-x  1 kghorbal  staff  102 Apr 21 20:15 keymaerax.jar -> /home/nfulton_unencrypted/KeYmaeraX/keymaerax-webui/target/scala-2.11/KeYmaeraX-Web-assembly-4.3.8.jar

**Comment by nrfulton** [comment]
Fixed and release script updated.
