### ISSUE TITLE
Better failure messages for dI

### ISSUE THREAD

**Issue by nrfulton** [LS-Lab/KeYmaeraX-release#31]
E.g. 

    "Could not prove that the invariant holds initially: Ante ==> BLAH"

Or:

    "Could not prove that the invariant is differentially inductive: 
    
    Ante ==> [{ODE}](BLAH)'. 
    
    FYI: (BLAH)' = insert derive(BLAH) here

**Comment by nrfulton** [comment]
Also applies to common error messages for other tactics. Solve is doing pretty reasonable now-a-days I think? Ghost could use better errors though.

**Comment by smitsch** [comment]
6a5c81860090089d3c091f70382a9886e33cb08a
