### ISSUE TITLE
solve fails sometimes on constant functions

### ISSUE THREAD

**Issue by nrfulton** [LS-Lab/KeYmaeraX-release#35]
The solve tactic sometimes fails on inputs like

    x'=v,v'=a*b

for a,b as functions even when it does not fail on

    x'=v,v'=a*b

for a,b as program variables.

**Comment by bbohrer** [comment]
Check for missing cases in the integrator.
This functionality (or part of it anyway) was added in for one of the new problems on Lab 3 this past semester, and I most likely just forgot a case in the process.

**Comment by nrfulton** [comment]
Thanks for the tip. I'll follow-up.

**Comment by nrfulton** [comment]
This bug is fixed as of now. Cannot reproduce on:

    Functions.
    R a(). R b().
    End.
    ProgramVariables.
    R x. R v.
    End.  
    Problem.
    x=0 &
    v=0 &
    a()>b()
    ->
    [{x'=v,v'=a()*b()}](x>=0)
    End.

using `implyR(1); solve(1)`.
