### ISSUE TITLE
/show links broken

### ISSUE THREAD

**Issue by nrfulton** [LS-Lab/KeYmaeraX-release#42]
/show links do not work even when the associated model/proof work when manually executed. Possibly relevant warning message:

`[WARN] [09/22/2017 18:44:38.291] [on-spray-can-akka.actor.default-dispatcher-5] [akka://on-spray-can/user/hydra] File-system path for base [] and Uri.Path [user/classpath:%2Fkeymaerax-projects%2Fitp17%2Fskydiver.kya/guest/mode/0] contains suspicious path segment [classpath:/keymaerax-projects/itp17/skydiver.kya], GET access was disallowed
`

**Comment by smitsch** [comment]
/show supports URLs relative to https://github.com/LS-Lab/KeYmaeraX-projects (e.g., `/show/dlds/dlds.kya`)
