### ISSUE TITLE
Polling Frequency Very High

### ISSUE THREAD

**Issue by Strikeskids** [LS-Lab/KeYmaeraX-release#52]
https://github.com/LS-Lab/KeYmaeraX-release/blob/master/keymaerax-webui/src/main/resources/js/controllers/provingawesome.js#L182

This 50ms pause between polls causes 50% of my CPU to be dedicated towards polling the status of the tactic. Could long-polling or a backoff policy be implemented to prevent this?

**Comment by aplatzer** [comment]
4.6.1

**Comment by Strikeskids** [comment]
There seems to be a similar bug if you kill the server while the web page is still open.
