### ISSUE TITLE
Tactic fails to compile

### ISSUE THREAD

**Issue by EphesosX** [LS-Lab/KeYmaeraX-release#58]
I'm getting the following error when trying to compile a tactic on Windows.

> Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -10
>         at java.lang.String.substring(Unknown Source)
>         at edu.cmu.cs.ls.keymaerax.api.ScalaTacticCompiler.$anonfun$compile$4(ScalaTacticCompiler.scala:41)
>         at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
>         at scala.collection.Iterator.foreach(Iterator.scala:941)
>         at scala.collection.Iterator.foreach$(Iterator.scala:941)
>         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
>         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
>         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
>         at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:95)
>         at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
>         at edu.cmu.cs.ls.keymaerax.api.ScalaTacticCompiler.compile(ScalaTacticCompiler.scala:37)
>         at edu.cmu.cs.ls.keymaerax.launcher.KeYmaeraX$.readTactic(KeYmaeraX.scala:452)
>         at edu.cmu.cs.ls.keymaerax.launcher.KeYmaeraX$.prove(KeYmaeraX.scala:635)
>         at edu.cmu.cs.ls.keymaerax.launcher.KeYmaeraX$.main(KeYmaeraX.scala:154)
>         at edu.cmu.cs.ls.keymaerax.launcher.Main$.main(Main.scala:86)
>         at edu.cmu.cs.ls.keymaerax.launcher.Main.main(Main.scala)

On line 41 of the tactic compiler, it attempts to search for forward slash and replace it with period, but Windows uses backslashes for file paths. I believe this causes the tactic compiler to fail, though I'm not sure why it would result in an index of -10 instead of -1 or 0.

https://github.com/LS-Lab/KeYmaeraX-release/blob/2cdb9ff37ed6c2e370e5f980ba28cf350004f567/keymaerax-webui/src/main/scala/edu/cmu/cs/ls/keymaerax/api/ScalaTacticCompiler.scala#L41

**Comment by bbohrer** [comment]
Hi,

Thanks for the bug report and for digging into the code - your diagnosis of the issue sounds correct to me. I assume you ran KeYmaera X from the Windows command line: could you post the exact command you ran to help us reproduce and fix this?

Until then, the Web UI shouldn't have this problem (run keymaerax.jar with no arguments). Sadly our Windows testing isn't quite as thorough as on Linux/Mac so sometimes bugs like this crop up.

**Comment by EphesosX** [comment]
The command:

java -Xss20M -jar ../../keymaerax.jar -mathkernel "C:\Program Files\Wolfram Research\Mathematica\12.0\MathKernel.exe" -jlink "C:\Program Files\Wolfram Research\Mathematica\12.0\SystemFiles\Links\JLink\SystemFiles\Libraries\Windows\JLinkNativeLibrary.dll" -prove passivesafetyabs_curvestraight_curvature.kyx -tactic PassiveSafetyCurvatureTacticGenerator.scala -out passivesafety.kyx.proof
