### ISSUE TITLE
^@ semantics

### ISSUE THREAD

**Issue by SweeWarman** [LS-Lab/KeYmaeraX-release#64]
Could someone kindly let me know where I can find the semantics for the "^@" symbol used in the KeYmaeraX language?

**Comment by nrfulton** [comment]
The ^@ symbol is KeYmaera X's syntax for the "dual" operator in hybrid grams. I.e., "^@" in KeYmaera X is the "^d" in Definition 2 of https://lfcps.org/pub/dGL-usubst.pdf. 

See also:

 - Pages 421-508 of André's textbook: https://www.springer.com/gp/book/9783319635873
 - lectures 16-18 at https://scs.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?#folderID=%22099e76b8-5dfa-4029-bd7b-94c24b860943%22&folderSets=15
 - Definition 3.1 in https://lfcps.org/pub/dGI.pdf

**Comment by aplatzer** [comment]
Differential game logic and hybrid games are stable just less-well tested than hybrid systems. Let us know if you run into any issues.
