### ISSUE TITLE
Differential Weaken for Diamond

### ISSUE THREAD

**Issue by L-Viard** [LS-Lab/KeYmaeraX-release#70]
Hello,

I am having some trouble proving a sequent that boils down to :

```
x = 1 -> < {x' = 1 & x = 1} > x = 1
```

From what I understand, the way KYX solves it is by solving the differential equation (\exists t_ ...) and the doing some basic logic / arithmetic.
The differential system I have is actually a bit uglier, thus I would rather not writing the various cuts to integrate it.

I would expect a rule such as :
```
G  |-  (Q -> P)
-------------------------
G  |-  < {f(x') & Q} > P
```

i.e.,  a Differential Weaken for diamond operator. Is there a way to achieve this ?

**Comment by smitsch** [comment]
In a diamond question, it is the system's responsibility to stay inside the evolution domain constraint Q while simultaneously achieving goal P. The axiom for diamond differential weakening is therefore 
```
<x'=f(x) & Q>P <-> <x'=f(x) & Q>(Q&P)
```
As a result, differential cuts on a diamond question don't actually help, they make the question harder. There are other techniques (see [An Axiomatic Approach to Liveness for Differential Equations](https://lfcps.org/pub/axiomatic-liveness.pdf)) that we are currently preparing to become more easily accessible in the upcoming release.

**Comment by L-Viard** [comment]
Thanks for the answer !
I understand your point for the diamond DW, I think me writing about DW was inaccurate as its motivation is different. The kind of axiom I'd use is more a "diamond initial state"-thing I guess : from the semantics of [dL](http://symbolaris.com/pub/freedL.pdf) we might want to consider the special case of r = 0 for differential evolution (Definition 5 - 2) , that is a "no-flow" situation. It has no use for the box operator (for we would first have to prove that no longer flow exists) , but it shoud be a sufficient condition for diamond questions, in which case the initial state should satisfy the evolution domain constraint. Thus the sequent rule I wrote before.

I haven't read about such a rule in the paper you kindly linked. As I mentionned, I don't think that this rule is mandatory : solving the ODE and then setting the flow duration to 0 (r in the article, t_ in kyx) is a work-around.
I think avoiding the dsolve part is yet a big deal, because we might not know how to do it, or for performance reasons.

**Comment by smitsch** [comment]
I think the differential skip axiom could be useful in your case:
```
Q&P -> <{x'=f(x) & Q}>P
```
The axiom is for the trivial case where the initial state already satisfies the property `P`, so following the ODE for duration 0 is enough. For liveness, `Q` is a proof obligation, not an assumption (`Q&P` instead of `Q->P`)

You can use it from the UI by switching to the tactic tab below the sequent and typing the following command into the text box labelled Fresh Steps:
```
useAt("DX diamond differential skip", 1)
```
where `1` is the index of the formula in the sequent.

**Comment by L-Viard** [comment]
Thanks, that's exactly what I was looking for !
