### ISSUE TITLE
Problem with Mathematica/Wolfram engine versions

### ISSUE THREAD

**Issue by JaimePSantos** [LS-Lab/KeYmaeraX-release#73]
Hello, 
After reading your building instructions, I noticed that JLink is required to be up to version 12.0. However, I cannot find a version of Wolfram Engine older than 12.2 and only have access to Mathematica 12.1/12.2. 
Is there any way to circumvent this, or do you know of somewhere I could find Wolfram Engine 12.0?
Thanks!

**Comment by smitsch** [comment]
Fixed in f3ef3c7bfa3f0a6047b4d772e70ea4c54d3dfee2
