### ISSUE TITLE
"Checking proof" hangs after combination of "expand," "expandAllDefs," and "tactic ... as"

### ISSUE THREAD

**Issue by bbohrer** [LS-Lab/KeYmaeraX-release#74]
Version: master (commit c8bd4d5b91)
Expected: Attached file proves successfully
Got: The following error message in the browser console:

errorReport.js:66 We're sorry, an internal safety check was violated, which may point to a bug. The safety check reports Core requirement failed: unique left-hand sides in substitutees USubstOne{(p(._0,._1)~>1=1), (q(._1,._2)~>1=1), (q(._0,._1)~>1=1), (p(._1,._2)~>1=1)}

Probable explanation: the "Checking proof" step looks through the proof tree for substitutions, then attempts to deduplicate the list of substitutions before substituting into the conclusion. When it looks through the proof tree, it finds "p" and "q" twice (each), but the deduplication logic fails because the arguments ("colored dots") are numbered differently in each occurrence: one is 0-indexed, the other is 1-indexed, so they are treated as distinct in the "deduplicate" step, but the core assertion fails because the names are not distinct.

Additional detail: When I get rid of the "tactic as ..." and just inline the tactic applications, the proof succeeds. So I suspect there's an interaction between the tactic definition mechanism and the substitution-scraping logic.

Bug priority level: I have several different workarounds I can use at the moment. Good to fix eventually because it showed up "in the wild" but it's absolutely a non-blocking issue.

[ArgNumberProofCheckBug.kyx.txt](https://github.com/LS-Lab/KeYmaeraX-release/files/6474852/ArgNumberProofCheckBug.kyx.txt)

**Comment by smitsch** [comment]
Fixed in aa14dc59c8cf61646aa649d0b12ed76bafaedeb4
