### ISSUE TITLE
Cannot export SharedDefinition of hybrid program binding unshared ProgramVariable

### ISSUE THREAD

**Issue by bbohrer** [LS-Lab/KeYmaeraX-release#78]
Here's a fun/extremely subtle one.
I got my KeYmaera X into a state where it could not export models that it had proved, because the variable binding checks for a SharedDefinition of an HP failed, even though it parsed initially.

If you open the Developer console on your browser, the exporter will give you the parse error (though in this case the archive I'm giving you already has the parse error, so you shouldn't need to open the console). The parse error says the hybrid program binds a program variable that isn't defined.

It seems to me that the problem is you'll get an error message if there *exists* an entry of the archive that does not declare the ProgramVariable that gets bound by the HP. So if you add new entries that declare fewer variables, you take a parsing entry and make it non-parsing.

Just to add an extra layer to it: this bug appears to only occur for variables that are may-bound but not must-bound, because the exporter has a nice variable binding check. So if I delete the loop, the bug goes away.

I wonder if there's a way to just export all the proofs even if they don't parse. Since it would be quite sad for proofs to ever get trapped inside the prover.

[HPExport.kyx.txt](https://github.com/LS-Lab/KeYmaeraX-release/files/6594487/HPExport.kyx.txt)

**Comment by smitsch** [comment]
Fixed with 72cef1d7b2dd5fe3d8ffc3f6ad6937c56631c7c8 and dc5bbeb1e89aa4655ee966f73871700d0c4d5f50
