### ISSUE TITLE
Java Versions in Build Instructions

### ISSUE THREAD

**Issue by nrfulton** [LS-Lab/KeYmaeraX-release#83]
The [build instructions](https://github.com/LS-Lab/KeYmaeraX-release/wiki/Building-Instructions) state:

> Install Java JDK 1.8 from http://www.java.com/getjava/ or from https://openjdk.java.net/ (JDK versions 1.9-12 also work but 1.8 is recommended for Scala; Java13 onwards does not work)

But using 1.12 results in the error following:

```
[error] /[redacted]/keymaerax-webui/src/main/scala/edu/cmu/cs/ls/keymaerax/hydra/ExtractTacticFromTrace.scala:75:38: value length is not a member of java.util.stream.Stream[String]
[error]     val (ts1t, ts2t) = if (ts2.lines.length <= 1) (ts1.trim, ts2.trim) else (ts1.trim, ts2.stripPrefix(indent))
[error]
```

Should I change the instructions in the wiki to simply recommend 1.8 (which is the only version I've had luck getting to consistently build across every environment)?

**Comment by smitsch** [comment]
Updated the build instructions
