### ISSUE TITLE
"internal safety check violated"

### ISSUE THREAD

**Issue by myradotzel** [LS-Lab/KeYmaeraX-release#88]
Internal safety check violated when proving something that should hold vacuously (attaching internal log and corresponding subgoal).
[log.txt](https://github.com/LS-Lab/KeYmaeraX-release/files/7281505/log.txt)
[subgoal.txt](https://github.com/LS-Lab/KeYmaeraX-release/files/7281507/subgoal.txt)

**Comment by smitsch** [comment]
The Web UI seems to have disconnected from the KeYmaera X server, or the server may have restarted. Reloading the page should fix the problem.
