### ISSUE TITLE
HOST accepts only 127.0.0.1

### ISSUE THREAD

**Issue by d01010101** [LS-Lab/KeYmaeraX-release#91]
I would like to access KeymaeraX remotely via the web. By default, its built-in web server only accept localhost requests. However, if I change the HOST setting in `keymaerax.conf` to any other value than 127.0.0.1 (a single IP or a list of IPs), `java -jar keymaerax.jar` silently exits instead of creating a web server.

**Comment by smitsch** [comment]
In addition to changing the HOST property, also set IS_HOSTED=true and be aware that Java properties files do not genuinely support comments (lines that start with # are ignored, but # anywhere else is content).

For example, HOST=IP # 127.0.0.1 will result in trying to bind to IP#127.0.0.1, which fails and the KeYmaera X server will not start.
