### ISSUE TITLE
Cannot prove lemmas due to overlapping UI elements

### ISSUE THREAD

**Issue by bbohrer** [LS-Lab/KeYmaeraX-release#93]
Version 4.9.8
Reproduce: 
1. Upload attached archive (New Model -> Structured)
2. Click Models -> "Two" -> "Run Stored Tactic"
3. Observe unclickable "Check" button per the attached screenshot

Expected: I can click the button to run the proofs of the lemmas
Got: I cannot click the button, ergo the main proof never finishes checking either. If I press Stop, I also get some other error message, by the way

Priority: There is a workaround (go back to Models page and check "One" manually) but it's a bit roundabout. I expect NII to use this feature, but not my WPI students, at least for a few months

![image](https://user-images.githubusercontent.com/1960801/148089528-922fb6e0-a430-4b14-a434-c921b85a1235.png)
[lemmaProveUIBug.kyx.txt](https://github.com/LS-Lab/KeYmaeraX-release/files/7808903/lemmaProveUIBug.kyx.txt)

**Comment by smitsch** [comment]
Closed accidentally
